### ISSUE TITLE
App testing framework

### ISSUE THREAD

**Issue by doron-cohen** [doron-cohen/antidot#17]
We should have a testing framework for ensuring that rules work correctly and we don't break anything. For example, for this `cargo` rule:

```yaml
  - name: cargo_home
    description: Rust Cargo home dir
    dotfile:
      name: .cargo
      is_dir: true
    actions:
      - type: migrate
        source: ${HOME}/.cargo
        dest: ${XDG_DATA_HOME}/cargo
        symlink: false
      - type: export
        key: CARGO_HOME
        value: ${XDG_DATA_HOME}/cargo
```
should be tested like:

1. running `cargo` commands.
2. ensuring the dotfile is there.
3. running antidot.
4. running `cargo` commands that interact with it's dotfiles (like reading or writing configuration).
5. ensure the `cargo` dotfile isn't there and that it did interact with it's dotfile in the new path.

This could be done using the Github Actions platform on both Linux and Mac machines. Also, defining tests should be easy (app installation command, pre-command, post-command, validation command). It could be written in Bash but Go is also an option.

Of course testing interactive applications will pose a bigger challenge or maybe even be too expensive to do.
