### ISSUE TITLE
List of files to implement

### ISSUE THREAD

**Issue by BeatLink** [doron-cohen/antidot#74]
This is just a general dump of files and folders that could be implemented. Each of these should be moved to their own issue

.xsession-errors
.yarnrc
.xsessionrc
.xinputrc
.Xauthority
.wget-hsts
.sudo_as_admin_successful
.profile
.pam_environment
.notable.json
.lmmsrc.xml
.ICEauthority
.gtkrc-xfce
.gitconfig
.face
.emulator_console_auth_token
.dmrc
.bashrc
.bash_logout
.bash_history
.yarn
.wine
.vscode-oss
.tor-browser
.themes
.ssh
.rednotebook
.pki
.notable
.mume
.linuxmint
.java
.icons
.hplip
.gphoto
.gnome
.dbus
.cinnamon

**Comment by BeatLink** [comment]
This is also a good place to look into https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by sunhasgothishaton** [comment]
Another list of files is https://wiki.debian.org/DotFilesList

**Comment by jimbrig** [comment]
also `.kube/config`:

```yaml
  - name: kube
    dotfile:
      name: .kube
      is_dir: true
    actions:
      - type: migrate
        source: ${HOME}/.kube/config
        dest: ${XDG_CONFIG_HOME}/kube/config
      - type: migrate
        source: ${HOME}/.kube/cache
        dest: ${XDG_CACHE_HOME}/kube/cache
      - type: export
        key: KUBECONFIG
        value: ${XDG_CONFIG_HOME}/kube/config
      - type: alias
        alias: kubectl
        command: kubectl --cache-dir="$XDG_CACHE_HOME"/kube/cache --kubeconfig "$XDG_CONFIG_HOME"/kube/config
```
